### PR TITLE
Improve server config file. Using TypeScript to describe it.

### PR DESCRIPTION
**Pull request by inglkruiz**
Hi, recently I worked on deploying a PoA network and I found difficult to understand what are the types of the values for the Server config file. Here I want to propose describing it using TypeScript assuming that it's easy to derivate the json structure from it.

### CODE REVIEW

**Comment by zivkovicmilos** [comment]
Hey @inglkruiz,

Thank you for the contribution, and I apologize for the long wait on any kind of feedback 🙏 

The configuration looks great, it's much cleaner than what was there earlier.

Since it's so nice now, I'm figuring we can have a dedicated section for it, instead of letting it hang as a reference that's hard to find 🙂 

I'll consult with the team and update you here on where we can put the ✨ polished config ✨

**Comment by GitesParti343** [comment]
88709e6

**Comment by GitesParti343** [comment]
👍

**Comment by GitesParti343** [comment]
> Hi, recently I worked on deploying a PoA network and I found difficult to understand what are the types of the values for the Server config file. Here I want to propose describing it using TypeScript assuming that it's easy to derivate the json structure from it.

88709e6

**Comment by zivkovicmilos** [comment]
Hey @inglkruiz,

Apologies for the late update.

Can you please resolve the merge conflicts with the base branch?

**Comment by zivkovicmilos** [comment]
Closing this PR due to inactivity.

Please open up a new one if you still want to contribute 🙏 

I apologize for somewhat late replies on this PR.

**Comment by inglkruiz** [comment]
@zivkovicmilos I will open a new PR, no worries ;)

**Pull request closed without merging**
